CREATE SCHEMA IF NOT EXISTS mySQL_database DEFAULT CHARACTER SET utf8;
USE mySQL_database;

CREATE TABLE IF NOT EXISTS todo
(
	id 			BIGINT AUTO_INCREMENT PRIMARY KEY,
	name 		VARCHAR (100),
	description VARCHAR (200)
);




  ENGINE = INNODB