spring:
  jpa:
    hibernate:
      dll-auto: validate
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/todolist
    driver-class-name: com.mysql.cj.jdbc.Driver