spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      dll-auto: validate
      package-scan: com.petproject
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/todolist
    driver-class-name: com.mysql.cj.jdbc.Driver